### ISSUE TITLE
Anki doesn't start gives error

### ISSUE THREAD

**Issue by russell359** [abdnh/aglish#1]
Hi, after installing aglish and restarting Anki I get this error and Anki fails to start. I'm running Anki 2.1.35
"Error during startup:
Traceback (most recent call last):
  File "aqt\main.py", line 119, in __init__
  File "aqt\main.py", line 175, in finish_ui_setup
  File "aqt\toolbar.py", line 49, in draw
  File "aqt\webview.py", line 378, in stdHtml
  File "aqt\gui_hooks.py", line 3024, in __call__
  File "C:\Users\russe\AppData\Roaming\Anki2\addons21\38866997\__init__.py", line 203, in on_webview_will_set_content
    (aqt.reviewer.Reviewer, aqt.previewer.Previewer, aqt.clayout.CardLayout),
AttributeError: module 'aqt' has no attribute 'clayout'"

**Comment by abdnh** [comment]
Seems something is odd with aqt.clayout in Anki 2.1.35
I've pushed an updated version to AnkiWeb that should fix it. Please let me know if it doesn't work for you.

**Comment by russell359** [comment]
Thank you. It's working for me now.
